version: '3.8'

services:
  redis:
    image: redis:6.2
    container_name: smartcache-redis
    ports:
      - "6379:6379"

  proxy:
    build: .
    container_name: smartcache-proxy
    ports:
      - 5001:5000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEFAULT_TTL=60
    depends_on:
      - redis